import '../modelos/animal.dart';
import 'donos_mock.dart';

// Dados de exemplo usados enquanto o aplicativo não conversa com a API.
const List<Animal> animaisMock = [
  Animal(
    nome: 'Dora',
    especie: 'Cachorro',
    raca: 'Chihuahua',
    sexo: 'fêmea',
    porte: 'pequeno',
    idade: '3 anos',
    peso: '3 kg',
    cor: 'caramelo',
    cidade: 'Formiga',
    tipo: TipoRegistro.adocao,
    castrado: true,
    vacinado: true,
    vermifugado: true,
    observacoes:
        'Convive bem com outros cachorros e já está acostumada com casa. '
        'Sente frio, precisa de roupinha no inverno.',
    dono: associacaoProtetora,
    foto: 'assets/animais/dora.jpg',
  ),
  Animal(
    nome: 'Thor',
    especie: 'Cachorro',
    raca: 'Border Collie',
    sexo: 'macho',
    porte: 'médio',
    idade: '2 anos',
    peso: '18 kg',
    cor: 'preto e branco',
    cidade: 'Formiga',
    tipo: TipoRegistro.adocao,
    castrado: true,
    vacinado: true,
    observacoes:
        'Muito ativo e obediente. Precisa de espaço para correr e de alguém '
        'com tempo para passear todos os dias.',
    dono: associacaoProtetora,
    foto: 'assets/animais/thor.jpg',
  ),
  Animal(
    nome: 'Mel',
    especie: 'Cachorro',
    raca: 'Jack Russell',
    sexo: 'fêmea',
    porte: 'pequeno',
    idade: '8 meses',
    peso: '6 kg',
    cor: 'branco e marrom',
    cidade: 'Formiga',
    tipo: TipoRegistro.adocao,
    vacinado: true,
    vermifugado: true,
    observacoes:
        'Filhote cheia de energia, acostumada com criança. Ainda está '
        'aprendendo a fazer as necessidades no lugar certo.',
    dono: marinaAlves,
    foto: 'assets/animais/mel.jpg',
  ),
  Animal(
    nome: 'Simba',
    especie: 'Gato',
    raca: 'Sem raça definida',
    sexo: 'macho',
    porte: 'médio',
    idade: '4 anos',
    peso: '5 kg',
    cor: 'laranja',
    cidade: 'Formiga',
    tipo: TipoRegistro.adocao,
    castrado: true,
    vacinado: true,
    vermifugado: true,
    observacoes:
        'Tranquilo e independente, passa boa parte do dia dormindo no sol. '
        'Indicado para apartamento, desde que as janelas tenham tela.',
    dono: associacaoProtetora,
    foto: 'assets/animais/simba.jpg',
  ),
  Animal(
    nome: 'Fred',
    especie: 'Gato',
    raca: 'Sem raça definida',
    sexo: 'macho',
    porte: 'médio',
    idade: '1 ano',
    peso: '4 kg',
    cor: 'rajado',
    cidade: 'Formiga',
    tipo: TipoRegistro.adocao,
    castrado: true,
    vacinado: true,
    observacoes:
        'Cresceu dentro de casa e não tem costume de rua. Se dá bem com '
        'outros gatos, mas estranha cachorro.',
    dono: marinaAlves,
    foto: 'assets/animais/fred.jpg',
  ),
  Animal(
    nome: 'Bidu',
    especie: 'Cachorro',
    raca: 'Poodle',
    sexo: 'macho',
    porte: 'pequeno',
    idade: '5 anos',
    peso: '7 kg',
    cor: 'branco',
    cidade: 'Formiga',
    tipo: TipoRegistro.perdido,
    observacoes:
        'Sumiu no bairro Santa Luzia no dia 18 de agosto. Estava de coleira '
        'vermelha e atende pelo nome.',
    dono: carlosPereira,
    foto: 'assets/animais/bidu.jpg',
  ),
  Animal(
    nome: 'Nina',
    especie: 'Cachorro',
    raca: 'Yorkshire',
    sexo: 'fêmea',
    porte: 'pequeno',
    idade: '2 anos',
    peso: '3 kg',
    cor: 'marrom e cinza',
    cidade: 'Formiga',
    tipo: TipoRegistro.perdido,
    observacoes:
        'Vista pela última vez perto da praça do bairro Centro. É medrosa e '
        'costuma se esconder embaixo de carro.',
    dono: joanaRibeiro,
    foto: 'assets/animais/nina.jpg',
  ),
  Animal(
    nome: 'Amora',
    especie: 'Gato',
    raca: 'Siamês',
    sexo: 'fêmea',
    porte: 'médio',
    idade: '3 anos',
    peso: '4 kg',
    cor: 'creme com pontas escuras',
    cidade: 'Formiga',
    tipo: TipoRegistro.perdido,
    observacoes:
        'Fugiu pela janela no dia 22 de agosto, no bairro São Vicente. '
        'Estava com coleira rosa.',
    dono: beatrizNogueira,
    foto: 'assets/animais/amora.jpg',
  ),
  Animal(
    nome: 'Filhote sem nome',
    especie: 'Cachorro',
    raca: 'Golden Retriever',
    sexo: 'macho',
    porte: 'médio',
    idade: '2 meses',
    peso: '5 kg',
    cor: 'creme',
    cidade: 'Formiga',
    tipo: TipoRegistro.resgate,
    observacoes:
        'Encontrado sozinho na avenida perto do posto. Precisa de lar '
        'temporário até conseguir adoção.',
    dono: luanaMartins,
    foto: 'assets/animais/filhote.jpg',
  ),
  Animal(
    nome: 'Marie',
    especie: 'Gato',
    raca: 'Sem raça definida',
    sexo: 'fêmea',
    porte: 'pequeno',
    idade: '5 meses',
    peso: '2 kg',
    cor: 'branco',
    cidade: 'Formiga',
    tipo: TipoRegistro.resgate,
    observacoes:
        'Filhote encontrada sozinha em um terreno baldio. Precisa de lar '
        'temporário e de acompanhamento veterinário.',
    dono: luanaMartins,
    foto: 'assets/animais/marie.jpg',
  ),
];
