import '../modelos/animal.dart';
import 'donos_mock.dart';

// Dados de exemplo usados enquanto o aplicativo não conversa com a API.
// As datas são contadas a partir de agora, e não fixas, para o feed não
// parecer parado no dia em que alguém abrir o aplicativo.
final DateTime _agora = DateTime.now();
DateTime _haDias(int dias) => _agora.subtract(Duration(days: dias));

final List<Animal> animaisMock = [
  Animal(
    nome: 'Dora',
    publicadoEm: _haDias(2),
    especie: 'Cachorro',
    raca: 'Chihuahua',
    sexo: 'fêmea',
    porte: 'pequeno',
    idade: '3 anos',
    peso: '3 kg',
    cor: 'caramelo',
    bairro: 'Centro',
    cidade: 'Formiga',
    tipo: TipoRegistro.adocao,
    castrado: true,
    vacinado: true,
    vermifugado: true,
    observacoes:
        'Convive bem com outros cachorros e já está acostumada com casa.',
    necessidadesEspeciais: 'Sente frio e precisa de roupinha no inverno',
    dono: associacaoProtetora,
    fotos: ['assets/animais/dora.jpg'],
  ),
  Animal(
    nome: 'Thor',
    publicadoEm: _haDias(9),
    especie: 'Cachorro',
    raca: 'Border Collie',
    sexo: 'macho',
    porte: 'médio',
    idade: '2 anos',
    peso: '18 kg',
    cor: 'preto e branco',
    bairro: 'Centro',
    cidade: 'Formiga',
    tipo: TipoRegistro.adocao,
    castrado: true,
    vacinado: true,
    observacoes:
        'Muito ativo e obediente. Precisa de espaço para correr e de alguém '
        'com tempo para passear todos os dias.',
    dono: associacaoProtetora,
    fotos: ['assets/animais/thor.jpg'],
  ),
  Animal(
    nome: 'Mel',
    publicadoEm: _haDias(0),
    especie: 'Cachorro',
    raca: 'Jack Russell',
    sexo: 'fêmea',
    porte: 'pequeno',
    idade: '8 meses',
    peso: '6 kg',
    cor: 'branco e marrom',
    bairro: 'Água Vermelha',
    cidade: 'Formiga',
    tipo: TipoRegistro.adocao,
    vacinado: true,
    vermifugado: true,
    observacoes:
        'Filhote cheia de energia, acostumada com criança. Ainda está '
        'aprendendo a fazer as necessidades no lugar certo.',
    dono: marinaAlves,
    fotos: ['assets/animais/mel.jpg'],
  ),
  Animal(
    nome: 'Simba',
    publicadoEm: _haDias(34),
    especie: 'Gato',
    raca: 'Sem raça definida',
    sexo: 'macho',
    porte: 'médio',
    idade: '4 anos',
    peso: '5 kg',
    cor: 'laranja',
    bairro: 'Centro',
    cidade: 'Formiga',
    tipo: TipoRegistro.adocao,
    castrado: true,
    vacinado: true,
    vermifugado: true,
    observacoes:
        'Tranquilo e independente, passa boa parte do dia dormindo no sol. '
        'Indicado para apartamento, desde que as janelas tenham tela.',
    necessidadesEspeciais: 'Precisa de ração específica para gato castrado',
    dono: associacaoProtetora,
    fotos: ['assets/animais/simba.jpg'],
  ),
  Animal(
    nome: 'Fred',
    publicadoEm: _haDias(17),
    especie: 'Gato',
    raca: 'Sem raça definida',
    sexo: 'macho',
    porte: 'médio',
    idade: '1 ano',
    peso: '4 kg',
    cor: 'rajado',
    bairro: 'Água Vermelha',
    cidade: 'Formiga',
    tipo: TipoRegistro.adocao,
    castrado: true,
    vacinado: true,
    observacoes:
        'Cresceu dentro de casa e não tem costume de rua. Se dá bem com '
        'outros gatos, mas estranha cachorro.',
    dono: marinaAlves,
    fotos: ['assets/animais/fred.jpg'],
  ),
  Animal(
    nome: 'Bidu',
    publicadoEm: _haDias(1),
    especie: 'Cachorro',
    raca: 'Poodle',
    sexo: 'macho',
    porte: 'pequeno',
    idade: '5 anos',
    peso: '7 kg',
    cor: 'branco',
    bairro: 'Santa Luzia',
    cidade: 'Formiga',
    tipo: TipoRegistro.perdido,
    observacoes:
        'Sumiu no bairro Santa Luzia no dia 18 de agosto. Estava de coleira '
        'vermelha e atende pelo nome.',
    necessidadesEspeciais: 'Toma remédio de uso contínuo para convulsão',
    dono: carlosPereira,
    fotos: ['assets/animais/bidu.jpg'],
  ),
  Animal(
    nome: 'Nina',
    publicadoEm: _haDias(5),
    especie: 'Cachorro',
    raca: 'Yorkshire',
    sexo: 'fêmea',
    porte: 'pequeno',
    idade: '2 anos',
    peso: '3 kg',
    cor: 'marrom e cinza',
    bairro: 'Centro',
    cidade: 'Formiga',
    tipo: TipoRegistro.perdido,
    observacoes:
        'Vista pela última vez perto da praça do bairro Centro. É medrosa e '
        'costuma se esconder embaixo de carro.',
    dono: joanaRibeiro,
    fotos: ['assets/animais/nina.jpg'],
  ),
  Animal(
    nome: 'Amora',
    publicadoEm: _haDias(12),
    especie: 'Gato',
    raca: 'Siamês',
    sexo: 'fêmea',
    porte: 'médio',
    idade: '3 anos',
    peso: '4 kg',
    cor: 'creme com pontas escuras',
    bairro: 'São Vicente',
    cidade: 'Formiga',
    tipo: TipoRegistro.perdido,
    observacoes:
        'Fugiu pela janela no dia 22 de agosto, no bairro São Vicente. '
        'Estava com coleira rosa.',
    dono: beatrizNogueira,
    fotos: ['assets/animais/amora.jpg'],
  ),
  Animal(
    nome: 'Filhote sem nome',
    publicadoEm: _haDias(3),
    especie: 'Cachorro',
    raca: 'Golden Retriever',
    sexo: 'macho',
    porte: 'médio',
    idade: '2 meses',
    peso: '5 kg',
    cor: 'creme',
    bairro: 'Vila Rica',
    cidade: 'Formiga',
    tipo: TipoRegistro.resgate,
    observacoes:
        'Encontrado sozinho na avenida perto do posto. Precisa de lar '
        'temporário até conseguir adoção.',
    dono: luanaMartins,
    fotos: ['assets/animais/filhote.jpg'],
  ),
  Animal(
    nome: 'Marie',
    publicadoEm: _haDias(21),
    especie: 'Gato',
    raca: 'Sem raça definida',
    sexo: 'fêmea',
    porte: 'pequeno',
    idade: '5 meses',
    peso: '2 kg',
    cor: 'branco',
    bairro: 'Bela Vista',
    cidade: 'Formiga',
    tipo: TipoRegistro.resgate,
    observacoes:
        'Filhote encontrada sozinha em um terreno baldio. Precisa de lar '
        'temporário e de acompanhamento veterinário.',
    dono: luanaMartins,
    fotos: ['assets/animais/marie.jpg'],
  ),
];
